# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f43ffd4f36a69e2b9b51c348788030bafec066d00496edd2c3e83c453d301eb982806121ddd57fa07f9612f3dd088ee382b466df7ce91747b428b354ec6da446

test:
  secret_key_base: 0b74fb7552d1679885beab5227c9f1a011e1dde745f68ab86598fb27afff941f391feecd69f67460ab200f4760759d04786ff29d4b2378d2651fb9b9096f4f06

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
